<?php include("../listeRequete.php"); ?>
<?php
	try{
	    // On se connecte a postgres
		$bdd = new PDO("pgsql:host=localhost;port=5432;dbname=pfe;user=root;password=glopglop");
  	}
	catch(Exception $e){
	    // En cas d'erreur, on affiche un message et on arrête tout
                die('Erreur : '.$e->getMessage()); 
	} 
	$reponseS=$bdd->prepare($req22);
	$reponseS->execute(array('id'=>$_GET['id']));

	
	
	$ch = curl_init();
	
	curl_setopt($ch, CURLOPT_URL, 'http://172.26.189.22:8080/api/internal/login');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, "{  \n   \"email\": \"admin\",  \n   \"password\": \"admin\"  \n }");

	$headers = array();
	$headers[] = 'Content-Type: application/json';
	$headers[] = 'Accept: application/json';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);
	$result=json_decode($result,true);	
	
	
	
	
	
	
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, 'http://172.26.189.22:8080/api/devices/'.$_GET['id']);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'DELETE');


	$headers = array();
	$headers[] = 'Accept: application/json';
	$headers[] = 'Grpc-Metadata-Authorization: Bearer '.$result['jwt'];
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	
	$result = curl_exec($ch);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);

	
	
	header('Location: ../index.php');
?>	

